/**
 * KnowledgeGraph — in-memory heterogeneous graph for the MCP server.
 *
 * Provides:
 *  - loadGraph(knowledgeRoot)   — reads pre-built graph/nodes.json + graph/edges.json
 *  - buildKnowledgeGraph(...)   — constructs graph from existing knowledge artifacts
 *                                 (fallback when pre-built files do not exist)
 *  - traverseGraph(...)         — BFS traversal with edgeType filter, maxDepth, and direction
 *
 * Node types  : file, symbol, module, feature, package
 * Edge types  : contains, calls, imports, depends_on, implements, similar_to
 *
 * All IDs follow the convention:
 *   file:    "file:<relPath>"         e.g. "file:tools/lib/cache.ts"
 *   symbol:  "symbol:<qualifiedName>" e.g. "symbol:OrderService.createOrder"
 *   module:  "module:<name>"          e.g. "module:tools"
 *   feature: "feature:<id>"           e.g. "feature:auth"
 *   package: "package:<name>"         e.g. "package:zod"
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type {
    GraphNode,
    GraphEdge,
    KnowledgeGraphData,
    TraversalResult,
    SymbolEntry,
    DependencyGraph,
    FileSummary,
    FeatureGroup,
} from '../../types.js';

// ── Constants ──────────────────────────────────────────────────────────────

/** All valid edge types, used for defaulting edgeTypes parameter. */
export const ALL_EDGE_TYPES: ReadonlyArray<GraphEdge['type']> = [
    'contains',
    'calls',
    'imports',
    'depends_on',
    'implements',
    'similar_to',
] as const;

/** Cap on nodes returned from a single traversal to prevent runaway responses. */
const MAX_TRAVERSAL_NODES = 500;

const MAX_FILE_SIZE_BYTES = 50 * 1024 * 1024; // 50 MB

// ── Disk I/O ───────────────────────────────────────────────────────────────

function safeReadJSON<T>(filePath: string): T | null {
    try {
        const stat = fs.statSync(filePath);
        if (stat.size > MAX_FILE_SIZE_BYTES) {
            process.stderr.write(`[knowledge-graph] WARNING: ${filePath} is too large, skipping\n`);
            return null;
        }
        const raw = fs.readFileSync(filePath, 'utf8');
        return JSON.parse(raw) as T;
    } catch {
        return null;
    }
}

/**
 * Loads the pre-built knowledge graph from:
 *   .knowledge/graph/nodes.json
 *   .knowledge/graph/edges.json
 *
 * Returns null if either file is missing or unreadable.
 */
export function loadGraph(knowledgeRoot: string): KnowledgeGraphData | null {
    const nodesPath = path.join(knowledgeRoot, 'graph', 'nodes.json');
    const edgesPath = path.join(knowledgeRoot, 'graph', 'edges.json');

    const nodes = safeReadJSON<GraphNode[]>(nodesPath);
    const edges = safeReadJSON<GraphEdge[]>(edgesPath);

    if (!nodes || !edges) return null;
    if (!Array.isArray(nodes) || !Array.isArray(edges)) return null;

    return { nodes, edges };
}

// ── Graph Construction ─────────────────────────────────────────────────────

/**
 * Builds a KnowledgeGraphData in-memory from existing knowledge artifacts.
 *
 * This is the fallback path used when pre-built graph/nodes.json and
 * graph/edges.json have not been generated by Phase 8 of the build pipeline.
 *
 * Edge construction:
 *   contains    — file → symbol (symbol belongs to file)
 *   calls       — symbol → symbol (call graph from SymbolEntry.calls)
 *   imports     — file → file (from DependencyGraph.fileDeps)
 *   depends_on  — module → module (from DependencyGraph.edges)
 *   similar_to  — feature → feature (from FeatureGroup.relatedFeatures)
 */
export function buildKnowledgeGraph(
    symbols: SymbolEntry[],
    dependencies: DependencyGraph,
    summaries: Record<string, FileSummary>,
    projectRoot: string,
    features?: FeatureGroup[]
): KnowledgeGraphData {
    const nodes: GraphNode[] = [];
    const edges: GraphEdge[] = [];
    const nodeIds = new Set<string>();

    function ensureNode(node: GraphNode): void {
        if (!nodeIds.has(node.id)) {
            nodeIds.add(node.id);
            nodes.push(node);
        }
    }

    function normalizeRelPath(absoluteOrRel: string): string {
        if (absoluteOrRel.startsWith(projectRoot)) {
            const rel = absoluteOrRel.slice(projectRoot.length);
            return rel.startsWith('/') || rel.startsWith('\\')
                ? rel.slice(1).replace(/\\/g, '/')
                : rel.replace(/\\/g, '/');
        }
        return absoluteOrRel.replace(/\\/g, '/');
    }

    // ── File nodes from summaries ──────────────────────────────────────────
    for (const [filePath, summary] of Object.entries(summaries)) {
        ensureNode({
            id: `file:${filePath}`,
            type: 'file',
            metadata: {
                path: filePath,
                purpose: (summary.purpose ?? '').slice(0, 200),
                module: filePath.split('/')[0] ?? '',
            },
        });
    }

    // ── Symbol nodes + contains/calls edges ───────────────────────────────
    for (const sym of symbols) {
        const relPath = normalizeRelPath(sym.file);
        const fileId = `file:${relPath}`;
        const symbolId = `symbol:${sym.qualifiedName}`;

        // Ensure file node exists
        ensureNode({
            id: fileId,
            type: 'file',
            metadata: {
                path: relPath,
                module: sym.module,
            },
        });

        // Symbol node
        ensureNode({
            id: symbolId,
            type: 'symbol',
            metadata: {
                qualifiedName: sym.qualifiedName,
                name: sym.name,
                file: relPath,
                line: String(sym.line),
                symbolType: sym.type,
                signature: (sym.signature ?? '').slice(0, 300),
                isExported: String(sym.isExported),
                module: sym.module,
            },
        });

        // contains: file → symbol
        edges.push({ source: fileId, target: symbolId, type: 'contains' });

        // calls: symbol → symbol (forward call graph)
        for (const callee of sym.calls ?? []) {
            edges.push({
                source: symbolId,
                target: `symbol:${callee}`,
                type: 'calls',
            });
        }
    }

    // ── Import edges from fileDeps ─────────────────────────────────────────
    for (const [fromFile, toFiles] of Object.entries(dependencies.fileDeps ?? {})) {
        const fromId = `file:${fromFile}`;
        ensureNode({ id: fromId, type: 'file', metadata: { path: fromFile } });

        for (const toFile of toFiles) {
            const toId = `file:${toFile}`;
            ensureNode({ id: toId, type: 'file', metadata: { path: toFile } });
            edges.push({ source: fromId, target: toId, type: 'imports' });
        }
    }

    // ── Module nodes + depends_on edges ───────────────────────────────────
    for (const moduleName of dependencies.nodes ?? []) {
        ensureNode({
            id: `module:${moduleName}`,
            type: 'module',
            metadata: { name: moduleName },
        });
    }
    for (const edge of dependencies.edges ?? []) {
        edges.push({
            source: `module:${edge.from}`,
            target: `module:${edge.to}`,
            type: 'depends_on',
        });
    }

    // ── Feature nodes + similar_to edges ──────────────────────────────────
    for (const feature of features ?? []) {
        ensureNode({
            id: `feature:${feature.id}`,
            type: 'feature',
            metadata: {
                name: feature.name,
                description: (feature.description ?? '').slice(0, 200),
                id: feature.id,
            },
        });

        for (const relatedId of feature.relatedFeatures ?? []) {
            edges.push({
                source: `feature:${feature.id}`,
                target: `feature:${relatedId}`,
                type: 'similar_to',
            });
        }
    }

    return { nodes, edges };
}

// ── Traversal ──────────────────────────────────────────────────────────────

/**
 * BFS traversal over the knowledge graph starting from startId.
 *
 * @param graph        The KnowledgeGraphData to traverse
 * @param startId      Node ID to start from (must be exact match)
 * @param edgeTypes    Edge type filter — only these edges are followed
 * @param maxDepth     Maximum BFS depth (1–5)
 * @param direction    'outgoing' follows source→target, 'incoming' follows target→source,
 *                     'both' follows both directions
 *
 * Returns an empty result when startId is not found in the graph.
 * Caps at MAX_TRAVERSAL_NODES to keep responses within budget.
 */
export function traverseGraph(
    graph: KnowledgeGraphData,
    startId: string,
    edgeTypes: string[],
    maxDepth: number,
    direction: 'outgoing' | 'incoming' | 'both'
): TraversalResult {
    const effectiveEdgeTypes = new Set(edgeTypes);
    const nodeMap = new Map<string, GraphNode>(graph.nodes.map((n) => [n.id, n]));

    // Fast start-node lookup
    const startNode = nodeMap.get(startId);
    if (!startNode) return { nodes: [], edges: [] };

    // Build adjacency indexes — filtered to requested edge types
    const outgoing = new Map<string, Array<{ target: string; edge: GraphEdge }>>();
    const incoming = new Map<string, Array<{ source: string; edge: GraphEdge }>>();

    for (const edge of graph.edges) {
        if (!effectiveEdgeTypes.has(edge.type)) continue;

        if (!outgoing.has(edge.source)) outgoing.set(edge.source, []);
        outgoing.get(edge.source)!.push({ target: edge.target, edge });

        if (!incoming.has(edge.target)) incoming.set(edge.target, []);
        incoming.get(edge.target)!.push({ source: edge.source, edge });
    }

    // BFS
    const visitedNodes = new Set<string>([startId]);
    const visitedEdgeKeys = new Set<string>();
    const resultNodes: Array<GraphNode & { depth: number }> = [{ ...startNode, depth: 0 }];
    const resultEdges: GraphEdge[] = [];

    const queue: Array<[string, number]> = [[startId, 0]];

    while (queue.length > 0 && resultNodes.length < MAX_TRAVERSAL_NODES) {
        const item = queue.shift();
        if (!item) break;
        const [currentId, currentDepth] = item;

        if (currentDepth >= maxDepth) continue;

        // Collect neighbors based on direction
        const neighbors: Array<{ id: string; edge: GraphEdge }> = [];

        if (direction === 'outgoing' || direction === 'both') {
            for (const { target, edge } of outgoing.get(currentId) ?? []) {
                neighbors.push({ id: target, edge });
            }
        }
        if (direction === 'incoming' || direction === 'both') {
            for (const { source, edge } of incoming.get(currentId) ?? []) {
                neighbors.push({ id: source, edge });
            }
        }

        for (const { id: neighborId, edge } of neighbors) {
            // Deduplicate edges
            const edgeKey = `${edge.source}→${edge.target}→${edge.type}`;
            if (!visitedEdgeKeys.has(edgeKey)) {
                visitedEdgeKeys.add(edgeKey);
                resultEdges.push(edge);
            }

            // New node — add to results and enqueue
            if (!visitedNodes.has(neighborId)) {
                visitedNodes.add(neighborId);
                const neighborNode = nodeMap.get(neighborId);
                if (neighborNode) {
                    resultNodes.push({ ...neighborNode, depth: currentDepth + 1 });
                    queue.push([neighborId, currentDepth + 1]);
                }
            }
        }
    }

    return { nodes: resultNodes, edges: resultEdges };
}

// ── Node Resolution ────────────────────────────────────────────────────────

/**
 * Resolves a user-supplied "start" string to matching node IDs in the graph.
 *
 * Resolution order:
 *  1. Exact ID match (e.g. "file:tools/cache.ts", "symbol:handler")
 *  2. Prefix-qualified match (e.g. "tools/cache.ts" → tries "file:tools/cache.ts")
 *  3. Suffix match for files (e.g. "cache.ts" matches any file ending in that)
 *  4. Symbol name match (case-insensitive name or qualifiedName)
 *  5. Module match
 *
 * Returns an empty array when nothing matches.
 */
export function resolveStartNodes(graph: KnowledgeGraphData, start: string): string[] {
    const startLower = start.toLowerCase();

    // 1. Exact ID match
    if (graph.nodes.some((n) => n.id === start)) return [start];

    // 2. Prefixed variants
    const prefixVariants = [
        `file:${start}`,
        `symbol:${start}`,
        `module:${start}`,
        `feature:${start}`,
        `package:${start}`,
    ];
    const prefixMatch = prefixVariants.filter((v) =>
        graph.nodes.some((n) => n.id === v)
    );
    if (prefixMatch.length > 0) return prefixMatch;

    // 3. Suffix match for files (e.g. "cache.ts" → "file:.../cache.ts")
    const suffixMatches = graph.nodes
        .filter(
            (n) =>
                n.type === 'file' &&
                (n.id.endsWith('/' + start) || n.id === `file:${start}`)
        )
        .map((n) => n.id);
    if (suffixMatches.length > 0) return suffixMatches;

    // 4. Case-insensitive name/qualifiedName match for symbols
    const symbolMatches = graph.nodes
        .filter(
            (n) =>
                n.type === 'symbol' &&
                (
                    (n.metadata['qualifiedName'] ?? '').toLowerCase() === startLower ||
                    (n.metadata['name'] ?? '').toLowerCase() === startLower
                )
        )
        .map((n) => n.id);
    if (symbolMatches.length > 0) return symbolMatches;

    // 5. Partial name/path match (substring)
    const partialMatches = graph.nodes
        .filter((n) => n.id.toLowerCase().includes(startLower))
        .map((n) => n.id);
    return partialMatches;
}
