#!/bin/sh
# Installs git hooks for the ai-code-knowledge project.
# Run: npm run install-hooks

set -e

HOOK_DIR=".git/hooks"

if [ ! -d "$HOOK_DIR" ]; then
  echo "Error: .git/hooks directory not found. Run this from the project root." >&2
  exit 1
fi

# ── pre-commit hook ──────────────────────────────────────────────────────────
# Runs the knowledge build (skipping vectors/features for speed) and stages
# .knowledge/ artifacts before each commit so the knowledge base stays current.
HOOK="$HOOK_DIR/pre-commit"

cat > "$HOOK" << 'HOOKEOF'
#!/bin/sh
# Auto-generated by scripts/install-hooks.sh — do not edit directly.
# Re-run "npm run install-hooks" to regenerate.
#
# Rebuilds the knowledge base (core phases only — skips slow vector/feature
# phases) and stages the result so the knowledge base is always committed.

set -e

echo "[pre-commit] Rebuilding knowledge base (--skip-vectors --skip-features)..."
npm run build-knowledge:skip-vectors 2>&1 | tail -5

echo "[pre-commit] Staging .knowledge/ artifacts..."
git add .knowledge/ 2>/dev/null || true

echo "[pre-commit] Done."
HOOKEOF

chmod +x "$HOOK"
echo "Pre-commit hook installed at $HOOK"
